spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001

spring:
  profiles: dev     #开发环境
  application:
    name: microservicecloud-eureka-config-client

eureka:
  instance:
    hostname: eureka7001.com

---
server:
  port: 7001

spring:
  profiles: test     #测试环境
  application:
    name: microservicecloud-eureka-config-client

eureka:
  instance:
    hostname: eureka7001.com
